### ISSUE TITLE
Missing requirement (pkginfo)?

### ISSUE THREAD

**Issue by Querela** [karec/extrapypi#4]
# How it happened

Calling `extrapypi start --filename extrapypi-config.cfg` immediatly after installing caused this error:

```python
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/myenv/bin/extrapypi", line 6, in <module>
    from extrapypi.manage import cli
  File "/home/user/miniconda3/envs/myenv/lib/python3.7/site-packages/extrapypi/manage.py", line 5, in <module>
    from extrapypi.app import create_app
  File "/home/user/miniconda3/envs/myenv/lib/python3.7/site-packages/extrapypi/app.py", line 31, in <module>
    from extrapypi import simple, utils, dashboard, user
  File "/home/user/miniconda3/envs/myenv/lib/python3.7/site-packages/extrapypi/simple/__init__.py", line 1, in <module>
    from . import views
  File "/home/user/miniconda3/envs/myenv/lib/python3.7/site-packages/extrapypi/simple/views.py", line 18, in <module>
    from extrapypi.commons.packages import create_release, get_store
  File "/home/user/miniconda3/envs/myenv/lib/python3.7/site-packages/extrapypi/commons/packages.py", line 11, in <module>
    from extrapypi import storage
  File "/home/user/miniconda3/envs/myenv/lib/python3.7/site-packages/extrapypi/storage/__init__.py", line 9, in <module>
    from .local import LocalStorage
  File "/home/user/miniconda3/envs/myenv/lib/python3.7/site-packages/extrapypi/storage/local.py", line 12, in <module>
    import pkginfo
ModuleNotFoundError: No module named 'pkginfo'
```

When I installed `pkginfo` it worked.

# My environment

* WSL (Windows, -> Linux-Emulation)
* Conda-Environment

# Solution

Include `pkginfo` into `install_requires` of the `setup.py`. It is already in the `requirements.txt` file.

**Comment by karec** [comment]
you are totally right it's missing from `setup.py`. I will try to add it as soon as I can but to be honest I didn't work on this project for a long time now and it will be low in my priority list

**Comment by karec** [comment]
you are totally right it's missing from `setup.py`. I will try to add it as soon as I can but to be honest I didn't work on this project for a long time now and it will be low in my priority list

**Comment by unigrup** [comment]
PR for this issue #5
